const Data = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: 'https://www.allrecipes.com/thmb/UXv_24LIE376MRgVvZDBJKa856w=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/24530-ButtermilkPancakes-II-mfs-4X3-3385-b9e08648074145d18c538731c2be4215.jpg',
    desc: `Pancakes are the hero of the breakfast table, and their very taste can even be described as “deeply breakfasty”: eggy, salty, just this side of sweet.`,
  },
  {
    id: 2,  
    title: 'burger',
    category: 'lunch',
    price: 13.99,
    img: 'https://media-cdn.tripadvisor.com/media/photo-s/1a/86/9d/db/canada-s-diner-double.jpg',
    desc: `A burger is a patty of ground beef grilled and placed between two halves of a bun. Slices of raw onion, lettuce, bacon, mayonnaise, and other ingredients add flavor.`,
  },
  {
    id: 3,
    title: 'caramel milkshake',
    category: 'shakes',
    price: 6.99,
    img: 'https://www.queensleeappetit.com/wp-content/uploads/2018/05/Salted-Caramel-Milkshake-9.jpg',
    desc: `This deliciously decadent caramel milkshake is quick and easy to make at home. vanilla ice cream, milk, and caramel–homemade or store-bought is just fine.`,
  },
  {
    id: 4,
    title: 'greek omelette',
    category: 'breakfast',
    price: 20.99,
    img: 'https://www.olivetomato.com/wp-content/uploads/2016/02/SAM4952-1.jpg',
    desc: `Try a Greek omelette for your next breakfast or brunch. Filled with chopped tomato, feta cheese, and kalamata olives, this is a quick and easy recipe to get your day started right.`,
  },
  {
    id: 5,
    title: 'pasta salad',
    category: 'lunch',
    price: 22.99,
    img: 'https://www.inspiredtaste.net/wp-content/uploads/2018/12/Easy-Pasta-Salad-Recipe-3-1200.jpg',
    desc: `Pasta salad is a salad dish prepared with one or more types of pasta, almost always chilled, and most often tossed in a vinegar, oil, or mayonnaise-based dressing`,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: 'https://www.whiskaffair.com/wp-content/uploads/2020/07/Oreo-Milkshake-2-3.jpg',
    desc: `Made with Oreo cookies, milk, vanilla ice cream, sugar, and chocolate sauce, this thick oreo shake recipe will take over your taste buds.`,
  },
  {
    id: 7,
    title: 'chocolate waffles',
    category: 'breakfast',
    price: 8.99,
    img: 'https://static.toiimg.com/thumb/52820018.cms?imgsize=137575&width=800&height=800',
    desc: `These chocolate waffles are a favorite. They offer a fun flavor variation on traditional waffles with a touch of cocoa.`,
  },
  {
    id: 8,
    title: 'chicken wrap',
    category: 'lunch',
    price: 12.99,
    img: 'https://laurenfitfoodie.com/wp-content/uploads/2023/05/bbqchickenwraps-21-scaled.jpg',
    desc: `Crispy Chicken Wrap is a tortilla wrap loaded with spiced fried chicken wrapped in bread crumbs , layed on a bed of green lettuce and pesto mayonnaise rolled and grilled to perfection.`,
  },
  {
    id: 9,
    title: 'strawberry shake',
    category: 'shakes',
    price: 16.99,
    img: 'https://www.oliviascuisine.com/wp-content/uploads/2021/06/strawberry-milkshake.jpg',
    desc: `Strawberry Milkshake prepared with this recipe is simply heaven because it uses bare minimum ingredients like fresh strawberries, milk and ice cream to bring out three good qualities of any shake; fresh, creamy and flavorful`,
  },
];
export default Data;
